export const dhakaArea = [
   { division_id: 1, name: "Dhanmondi" },
   { division_id: 2, name: "Gulshan" },
   { division_id: 3, name: "Banani" },
   { division_id: 4, name: "Mohammadpur" },
   { division_id: 5, name: "Uttara" },
   { division_id: 6, name: "Mirpur" },
   { division_id: 7, name: "Bashundhara" },
   { division_id: 8, name: "Motijheel" },
   { division_id: 9, name: "Farmgate" },
   { division_id: 10, name: "Paltan" },
   { division_id: 11, name: "Malibagh" },
   { division_id: 12, name: "Badda" },
   { division_id: 13, name: "Rampura" },
   { division_id: 14, name: "Baridhara" },
   { division_id: 15, name: "Shahbagh" },
   { division_id: 16, name: "Tejgaon" },
   { division_id: 17, name: "Khilgaon" },
   { division_id: 18, name: "Jatrabari" },
   { division_id: 19, name: "Savar" },
   { division_id: 20, name: "Keraniganj" },
   { division_id: 21, name: "Lalbagh" },
   { division_id: 22, name: "Azimpur" },
   { division_id: 23, name: "Old Dhaka" },
   { division_id: 24, name: "Demra" },
   { division_id: 25, name: "Kamrangirchar" },
   { division_id: 26, name: "Hazaribagh" },
   { division_id: 27, name: "Khilkhet" },
   { division_id: 28, name: "Niketan" },
   { division_id: 29, name: "Cantonment" },
   { division_id: 30, name: "Shyamoli" },
   { division_id: 31, name: "Mohakhali" },
   { division_id: 32, name: "Tongi" },
   { division_id: 33, name: "Dohar" },
   { division_id: 34, name: "Nawabganj" },
   { division_id: 35, name: "Kafrul" },
   { division_id: 36, name: "Agargaon" },
   { division_id: 37, name: "Green Road" },
   { division_id: 38, name: "Eskaton" },
   { division_id: 39, name: "Mogbazar" },
   { division_id: 40, name: "Bangshal" },
];
